// Code generated by go-swagger; DO NOT EDIT.

package airlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAirlinesParams creates a new GetAirlinesParams object
// with the default values initialized.
func NewGetAirlinesParams() *GetAirlinesParams {

	return &GetAirlinesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAirlinesParamsWithTimeout creates a new GetAirlinesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAirlinesParamsWithTimeout(timeout time.Duration) *GetAirlinesParams {

	return &GetAirlinesParams{

		timeout: timeout,
	}
}

// NewGetAirlinesParamsWithContext creates a new GetAirlinesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAirlinesParamsWithContext(ctx context.Context) *GetAirlinesParams {

	return &GetAirlinesParams{

		Context: ctx,
	}
}

// NewGetAirlinesParamsWithHTTPClient creates a new GetAirlinesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAirlinesParamsWithHTTPClient(client *http.Client) *GetAirlinesParams {

	return &GetAirlinesParams{
		HTTPClient: client,
	}
}

/*GetAirlinesParams contains all the parameters to send to the API endpoint
for the get airlines operation typically these are written to a http.Request
*/
type GetAirlinesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get airlines params
func (o *GetAirlinesParams) WithTimeout(timeout time.Duration) *GetAirlinesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get airlines params
func (o *GetAirlinesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get airlines params
func (o *GetAirlinesParams) WithContext(ctx context.Context) *GetAirlinesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get airlines params
func (o *GetAirlinesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get airlines params
func (o *GetAirlinesParams) WithHTTPClient(client *http.Client) *GetAirlinesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get airlines params
func (o *GetAirlinesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAirlinesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
