// Code generated by go-swagger; DO NOT EDIT.

package airlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/amadeusitgroup/miniapp/itineraries-server/pkg/models"
)

// GetAirlinesReader is a Reader for the GetAirlines structure.
type GetAirlinesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAirlinesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAirlinesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAirlinesOK creates a GetAirlinesOK with default headers values
func NewGetAirlinesOK() *GetAirlinesOK {
	return &GetAirlinesOK{}
}

/*GetAirlinesOK handles this case with default header values.

list of airlines
*/
type GetAirlinesOK struct {
	Payload []*models.Airline
}

func (o *GetAirlinesOK) Error() string {
	return fmt.Sprintf("[GET /airlines][%d] getAirlinesOK  %+v", 200, o.Payload)
}

func (o *GetAirlinesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
