// Code generated by go-swagger; DO NOT EDIT.

package airlines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/amadeusitgroup/miniapp/storage/pkg/models"
)

// GetAirlinesOKCode is the HTTP code returned for type GetAirlinesOK
const GetAirlinesOKCode int = 200

/*GetAirlinesOK list of airlines

swagger:response getAirlinesOK
*/
type GetAirlinesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Airline `json:"body,omitempty"`
}

// NewGetAirlinesOK creates GetAirlinesOK with default headers values
func NewGetAirlinesOK() *GetAirlinesOK {

	return &GetAirlinesOK{}
}

// WithPayload adds the payload to the get airlines o k response
func (o *GetAirlinesOK) WithPayload(payload []*models.Airline) *GetAirlinesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airlines o k response
func (o *GetAirlinesOK) SetPayload(payload []*models.Airline) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirlinesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Airline, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
