// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/net.amadeus.miniapp.itineraries.v1+json"
  ],
  "produces": [
    "application/net.amadeus.miniapp.itineraries.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "needs to add a description",
    "title": "An Itineraries server application",
    "version": "1.0.0"
  },
  "paths": {
    "/itineraries": {
      "get": {
        "tags": [
          "itineraries"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "from",
            "in": "query"
          },
          {
            "type": "string",
            "name": "to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list of itineraries",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/itinerary"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "itinerary": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "description": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/itineraryStep"
          },
          "readOnly": true
        },
        "distance": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    },
    "itineraryStep": {
      "type": "string"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/net.amadeus.miniapp.itineraries.v1+json"
  ],
  "produces": [
    "application/net.amadeus.miniapp.itineraries.v1+json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "needs to add a description",
    "title": "An Itineraries server application",
    "version": "1.0.0"
  },
  "paths": {
    "/itineraries": {
      "get": {
        "tags": [
          "itineraries"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "from",
            "in": "query"
          },
          {
            "type": "string",
            "name": "to",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list of itineraries",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/itinerary"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "itinerary": {
      "type": "object",
      "properties": {
        "completed": {
          "type": "boolean"
        },
        "description": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/itineraryStep"
          },
          "readOnly": true
        },
        "distance": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        }
      }
    },
    "itineraryStep": {
      "type": "string"
    }
  }
}`))
}
