apiVersion: batch/v1
kind: Job
metadata:
  name: import-courses
spec:
  template:
    metadata:
      name: import-courses
    spec:
      containers:
      - name: courses-importer
        image: localhost:5000/importer
        command:
         - "bin/bash"
         - "-c"
         - "mongoimport --host=mongo.default.svc.cluster.local -d miniapp -c courses --type csv --file courses.dat --fieldFile=courses_schema.dat"
      restartPolicy: Never
