kind: ReplicationController
apiVersion: v1
metadata:
  name: mongo-3
spec:
  replicas: 1
  selector:
    name: mongo-node-3
    role: mongo
    environment: test
  template:
    spec:
      containers:
        - name: mongo-node-3
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
              hostPort: 4000
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
      volumes:
        - name: mongo-persistent-storage
          emptyDir: {}
    metadata:
      labels:
        name: mongo-node-3
        role: mongo
        environment: test
