// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi An Itineraries server application
needs to add a description


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/net.amadeus.miniapp.itineraries.v1+json

    Produces:
    - application/json

swagger:meta
*/
package restapi
