/*
Copyright 2018 Amadeus SaS All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"log"
	"os"

	"github.com/amadeusitgroup/miniapp/storage/cmd/config"
	"github.com/amadeusitgroup/miniapp/storage/pkg/gen/restapi"
	"github.com/amadeusitgroup/miniapp/storage/pkg/gen/restapi/operations"
	loads "github.com/go-openapi/loads"
	flag "github.com/spf13/pflag"
)

func main() {

	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	var server *restapi.Server // make sure init is called

	// Custom Vars
	flag.StringVar(&config.MongoHost, "mongo-host", "mongo", "the mongo service name")
	flag.IntVar(&config.MongoPort, "mongo-port", 27017, "the port of the mongo service")

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  storage-server [OPTIONS]\n\n")

		title := "miniapp storage"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "needs to add a description"
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}

	flag.Parse()

	api := operations.NewStorageAPI(swaggerSpec)
	server = restapi.NewServer(api)
	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}

}
