/*

MIT License

Copyright (c) 2019 Amadeus s.a.s.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
// Code generated by go-swagger; DO NOT EDIT.

package main

import (
	"fmt"
	"os"

	loads "github.com/go-openapi/loads"
	log "github.com/sirupsen/logrus"
	flag "github.com/spf13/pflag"

	"github.com/amadeusitgroup/miniplanes/itineraries-server/cmd/config"
	"github.com/amadeusitgroup/miniplanes/itineraries-server/pkg/gen/restapi"
	"github.com/amadeusitgroup/miniplanes/itineraries-server/pkg/gen/restapi/operations"
)

const (
	storageHostParamName = "storage-host"
	storageHostDefault   = "storage"
	storagePortParamName = "storage-port"
	storagePortDefault   = 12345
)

func init() {
	// Output to stdout instead of the default stderr
	// TODO: SetOutput by out parameter
	log.SetOutput(os.Stdout)

	// TODO: set formatter JSONFormatter or default ASCII formatter
	formatter := &log.TextFormatter{
		FullTimestamp: true,
	}
	log.SetFormatter(formatter)
}

func main() {
	swaggerSpec, err := loads.Embedded(restapi.SwaggerJSON, restapi.FlatSwaggerJSON)
	if err != nil {
		log.Fatalln(err)
	}

	var server *restapi.Server // make sure init is called
	flag.IntVar(&config.StoragePort, storagePortParamName, storagePortDefault, "the port of storage service")
	flag.StringVar(&config.StorageHost, storageHostParamName, storageHostDefault, "the name of the storage service")
	var verbosity string
	flag.StringVar(&verbosity, "verbosity", log.WarnLevel.String(), "Verbosity level: debug, info, warn, error, fatal, panic")

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, "Usage:\n")
		fmt.Fprint(os.Stderr, "  itineraries-server [OPTIONS]\n\n")

		title := "miniplanes itineraries-server"
		fmt.Fprint(os.Stderr, title+"\n\n")
		desc := "needs to add a description"
		if desc != "" {
			fmt.Fprintf(os.Stderr, desc+"\n\n")
		}
		fmt.Fprintln(os.Stderr, flag.CommandLine.FlagUsages())
	}

	flag.Parse()

	lvl, err := log.ParseLevel(verbosity)
	if err != nil {
		log.Errorf("Verbosity level must be:  debug, info, warn, error, fatal, panic. Set to 'info' by default.")
		lvl = log.InfoLevel
	}
	log.SetLevel(lvl)
	log.Infof("Running itineraries-server version: %s", config.Version)
	log.Infof("Running itineraries-server with %s: %s", storageHostParamName, config.StorageHost)
	log.Infof("Running itineraries-server with %s: %d", storagePortParamName, config.StoragePort)
	log.Infof("Running storage with verbosity: %s", lvl.String())

	api := operations.NewItinerariesAPI(swaggerSpec)
	server = restapi.NewServer(api)
	defer server.Shutdown()

	server.ConfigureAPI()
	if err := server.Serve(); err != nil {
		log.Fatalln(err)
	}
	log.Info("Thanks for running itineraries-server. Hope it was OK")

}
