kind: Service
apiVersion: v1
metadata:
  name: itineraries-server
  labels:
    name:  itineraries-server
spec:
  selector:
    app: itineraries-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itineraries-server-deployment
  labels:
    app: itineraries-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itineraries-server
  template:
    metadata:
      labels:
        app: itineraries-server
    spec:
      containers:
      - name: itineraries-server
        image: localhost:5000/miniplanes
        imagePullPolicy: Always
        command: ["/itineraries-server"]
        args: ["--port=8080", "--host=0.0.0.0"]
        ports:
        - containerPort: 8080
