// Code generated by go-swagger; DO NOT EDIT.

package liveness

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new liveness API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for liveness API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetLive get live API
*/
func (a *Client) GetLive(params *GetLiveParams) (*GetLiveOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetLiveParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetLive",
		Method:             "GET",
		PathPattern:        "/live",
		ProducesMediaTypes: []string{"application/net.amadeus.miniapp.itineraries.v1+json"},
		ConsumesMediaTypes: []string{"application/net.amadeus.miniapp.itineraries.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetLiveReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetLiveOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
