kind: Service
apiVersion: v1
metadata:
  name: itineraries-server
  labels:
    name:  itineraries-server
spec:
  selector:
    app: itineraries-server
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itineraries-server-deployment
  labels:
    app: itineraries-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itineraries-server
  template:
    metadata:
      labels:
        app: itineraries-server
    spec:
      containers:
      - name: itineraries-server
        image: itineraries-server:latest
        imagePullPolicy: Never
        command: ["/itineraries-server"]
        args: ["--port=8081", "--host=0.0.0.0"]
        ports:
        - containerPort: 8081
