kind: Service
apiVersion: v1
metadata:
  name: storage
  labels:
    name: storage
spec:
  selector:
    app: storage
  ports:
  - protocol: TCP
    port: 33775
    targetPort: 33775
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      containers:
      - name: storage
        image: storage:latest
        imagePullPolicy: Never
        command: ["/storage"]
        args: ["--port=33775", "--mongo-host=mongo"]
        ports:
        - containerPort: 33775
