kind: Service
apiVersion: v1
metadata:
  name: ui
  labels:
    name: ui
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ui:latest
        imagePullPolicy: Never
        command: ["/ui"]
        args: ["--port=8090", "--host=0.0.0.0"]
        ports:
        - containerPort: 8090
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5