// Code generated by go-swagger; DO NOT EDIT.

package airports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/amadeusitgroup/miniapp/itineraries-server/pkg/models"
)

// GetAirportsReader is a Reader for the GetAirports structure.
type GetAirportsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAirportsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAirportsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAirportsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAirportsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAirportsOK creates a GetAirportsOK with default headers values
func NewGetAirportsOK() *GetAirportsOK {
	return &GetAirportsOK{}
}

/*GetAirportsOK handles this case with default header values.

list of airports
*/
type GetAirportsOK struct {
	Payload []*models.Airport
}

func (o *GetAirportsOK) Error() string {
	return fmt.Sprintf("[GET /airports][%d] getAirportsOK  %+v", 200, o.Payload)
}

func (o *GetAirportsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAirportsBadRequest creates a GetAirportsBadRequest with default headers values
func NewGetAirportsBadRequest() *GetAirportsBadRequest {
	return &GetAirportsBadRequest{}
}

/*GetAirportsBadRequest handles this case with default header values.

generic error response
*/
type GetAirportsBadRequest struct {
	Payload *models.Error
}

func (o *GetAirportsBadRequest) Error() string {
	return fmt.Sprintf("[GET /airports][%d] getAirportsBadRequest  %+v", 400, o.Payload)
}

func (o *GetAirportsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAirportsDefault creates a GetAirportsDefault with default headers values
func NewGetAirportsDefault(code int) *GetAirportsDefault {
	return &GetAirportsDefault{
		_statusCode: code,
	}
}

/*GetAirportsDefault handles this case with default header values.

generic error response
*/
type GetAirportsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get airports default response
func (o *GetAirportsDefault) Code() int {
	return o._statusCode
}

func (o *GetAirportsDefault) Error() string {
	return fmt.Sprintf("[GET /airports][%d] GetAirports default  %+v", o._statusCode, o.Payload)
}

func (o *GetAirportsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
