swagger: "2.0"
info:
  description: needs to add a description
  title: An Itineraries server application
  version: 1.0.0
consumes:
- application/net.amadeus.miniapp.itineraries.v1+json
produces:
- application/net.amadeus.miniapp.itineraries.v1+json
schemes:
- http
#- https
paths:
  /itineraries:
    get:
      tags:
        - itineraries
      parameters:
        - name: from
          in: query
          type: string
        - name: to
          in: query
          type: string
      responses:
        200:
          description: list of itineraries
          schema:
            type: array
            items:
              $ref: "#/definitions/itinerary"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  itinerary:
    type: object
    properties:
      distance:
        type: integer
        format: int64
        readOnly: true
      description:
        type: array
        items:
          $ref: "#/definitions/itineraryStep"
        readOnly: true
      completed:
        type: boolean
  itineraryStep:
    type: string
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
