// Code generated by go-swagger; DO NOT EDIT.

package itineraries

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new itineraries API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for itineraries API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetItineraries get itineraries API
*/
func (a *Client) GetItineraries(params *GetItinerariesParams) (*GetItinerariesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetItinerariesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetItineraries",
		Method:             "GET",
		PathPattern:        "/itineraries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/net.amadeus.miniapp.itineraries.v1+json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetItinerariesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetItinerariesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
