/*

MIT License

Copyright (c) 2019 Amadeus s.a.s.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
// Code generated by go-swagger; DO NOT EDIT.

package readiness

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReadyParams creates a new GetReadyParams object
// with the default values initialized.
func NewGetReadyParams() *GetReadyParams {

	return &GetReadyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReadyParamsWithTimeout creates a new GetReadyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReadyParamsWithTimeout(timeout time.Duration) *GetReadyParams {

	return &GetReadyParams{

		timeout: timeout,
	}
}

// NewGetReadyParamsWithContext creates a new GetReadyParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetReadyParamsWithContext(ctx context.Context) *GetReadyParams {

	return &GetReadyParams{

		Context: ctx,
	}
}

// NewGetReadyParamsWithHTTPClient creates a new GetReadyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetReadyParamsWithHTTPClient(client *http.Client) *GetReadyParams {

	return &GetReadyParams{
		HTTPClient: client,
	}
}

/*GetReadyParams contains all the parameters to send to the API endpoint
for the get ready operation typically these are written to a http.Request
*/
type GetReadyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get ready params
func (o *GetReadyParams) WithTimeout(timeout time.Duration) *GetReadyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ready params
func (o *GetReadyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ready params
func (o *GetReadyParams) WithContext(ctx context.Context) *GetReadyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ready params
func (o *GetReadyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ready params
func (o *GetReadyParams) WithHTTPClient(client *http.Client) *GetReadyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ready params
func (o *GetReadyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetReadyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
