// Code generated by go-swagger; DO NOT EDIT.

package airports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/amadeusitgroup/miniapp/storage/pkg/models"
)

// GetAirportsOKCode is the HTTP code returned for type GetAirportsOK
const GetAirportsOKCode int = 200

/*GetAirportsOK list of airports

swagger:response getAirportsOK
*/
type GetAirportsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Airport `json:"body,omitempty"`
}

// NewGetAirportsOK creates GetAirportsOK with default headers values
func NewGetAirportsOK() *GetAirportsOK {

	return &GetAirportsOK{}
}

// WithPayload adds the payload to the get airports o k response
func (o *GetAirportsOK) WithPayload(payload []*models.Airport) *GetAirportsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airports o k response
func (o *GetAirportsOK) SetPayload(payload []*models.Airport) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirportsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Airport, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetAirportsBadRequestCode is the HTTP code returned for type GetAirportsBadRequest
const GetAirportsBadRequestCode int = 400

/*GetAirportsBadRequest generic error response

swagger:response getAirportsBadRequest
*/
type GetAirportsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAirportsBadRequest creates GetAirportsBadRequest with default headers values
func NewGetAirportsBadRequest() *GetAirportsBadRequest {

	return &GetAirportsBadRequest{}
}

// WithPayload adds the payload to the get airports bad request response
func (o *GetAirportsBadRequest) WithPayload(payload *models.Error) *GetAirportsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airports bad request response
func (o *GetAirportsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirportsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetAirportsDefault generic error response

swagger:response getAirportsDefault
*/
type GetAirportsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAirportsDefault creates GetAirportsDefault with default headers values
func NewGetAirportsDefault(code int) *GetAirportsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAirportsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get airports default response
func (o *GetAirportsDefault) WithStatusCode(code int) *GetAirportsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get airports default response
func (o *GetAirportsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get airports default response
func (o *GetAirportsDefault) WithPayload(payload *models.Error) *GetAirportsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get airports default response
func (o *GetAirportsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAirportsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
