// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Airport airport
// swagger:model airport
type Airport struct {

	// airport ID
	AirportID int64 `json:"AirportID,omitempty"`

	// city
	City string `json:"City,omitempty"`

	// country
	Country string `json:"Country,omitempty"`

	// d s t
	DST string `json:"DST,omitempty"`

	// i a t a
	IATA string `json:"IATA,omitempty"`

	// i c a o
	ICAO string `json:"ICAO,omitempty"`

	// latitude
	Latitude float64 `json:"Latitude,omitempty"`

	// longitude
	Longitude float64 `json:"Longitude,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// t z
	TZ string `json:"TZ,omitempty"`

	// timezone
	Timezone string `json:"timezone,omitempty"`
}

// Validate validates this airport
func (m *Airport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Airport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Airport) UnmarshalBinary(b []byte) error {
	var res Airport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
