// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ItineraryStep itinerary step
// swagger:model itineraryStep
type ItineraryStep struct {

	// from
	From string `json:"from,omitempty"`

	// to
	To string `json:"to,omitempty"`
}

// Validate validates this itinerary step
func (m *ItineraryStep) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ItineraryStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ItineraryStep) UnmarshalBinary(b []byte) error {
	var res ItineraryStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
